version: '3'

services:
  app:
    image: kevinduy/reactjs
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "8000:8000"
    links:
      - mongodb
    tty: true

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .docker/db:/data/db
